# Enable/Disable Built-In Features
aha_board: false
question_board: false
projects: true

# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
sidebar:
  
  - 
    label: "Community"
    url: "http://community.golearntocode.com/c/kiei-925-winter-2016"
    icon: fa-comments
